import os
import urllib.request
from fpdf import FPDF

def ensure_korean_font():
    """PDF 생성을 위한 한글 폰트(나눔고딕) 자동 다운로드 및 경로 반환"""
    font_path = "NanumGothic.ttf"
    if not os.path.exists(font_path):
        # 폰트가 없으면 구글 폰트에서 직접 다운로드
        url = "https://github.com/google/fonts/raw/main/ofl/nanumgothic/NanumGothic-Regular.ttf"
        urllib.request.urlretrieve(url, font_path)
    return font_path

class AuditReportPDF(FPDF):
    def header(self):
        # 헤더: 로고/타이틀
        self.set_font('Nanum', '', 16)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, 'KB X-Ray | AI Compliance Audit Report', border=False, ln=True, align='L')
        self.line(10, 22, 200, 22)  # 구분선
        self.ln(10)

    def footer(self):
        # 푸터: 페이지 번호
        self.set_y(-15)
        self.set_font('Nanum', '', 9)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f'Page {self.page_no()} - Generated by KB X-Ray Prototype', align='C')

def generate_pdf(record):
    """분석 레코드를 입력받아 PDF byte 데이터를 반환"""
    font_path = ensure_korean_font()
    pdf = AuditReportPDF()
    
    # 한글 폰트 등록
    pdf.add_font('Nanum', '', font_path) 
    pdf.add_page()
    
    report = record.get('report', {})
    
    # 1. 분석 개요
    pdf.set_font('Nanum', '', 15)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, '1. 분석 개요', ln=True)
    
    pdf.set_font('Nanum', '', 11)
    pdf.set_text_color(70, 70, 70)
    pdf.cell(0, 8, f" - 분석 ID: {record.get('id')}", ln=True)
    pdf.cell(0, 8, f" - 분석 일시: {record.get('date')}", ln=True)
    pdf.cell(0, 8, f" - 분석 모드: {record.get('mode')}", ln=True)
    pdf.cell(0, 8, f" - 기준 문서: {record.get('file_name', '직접 입력 데이터')}", ln=True)
    pdf.ln(8)
    
    # 2. 리스크 스코어
    pdf.set_font('Nanum', '', 15)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, '2. 종합 위험도 평가', ln=True)
    pdf.set_font('Nanum', '', 11)
    
    level_text = report.get('risk_level', '알 수 없음')
    # 위험도에 따른 색상 변경
    if "위험" in level_text:
        pdf.set_text_color(200, 50, 50)  # Red
    else:
        pdf.set_text_color(50, 150, 50)  # Green
        
    pdf.cell(0, 8, f" - 최종 위험 점수: {report.get('final_risk_score', 0)}점 ({level_text})", ln=True)
    
    pdf.set_text_color(70, 70, 70)
    pdf.cell(0, 8, f" - 약관 독소조항 점수: {report.get('term_risk_score', 0)}점", ln=True)
    pdf.cell(0, 8, f" - 불완전판매 위험 점수: {report.get('sales_risk_score', 0)}점", ln=True)
    pdf.ln(8)
    
    # 3. 실무 조치 가이드 (Action Items)
    pdf.set_font('Nanum', '', 15)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, '3. 컴플라이언스 조치 가이드 (Action Items)', ln=True)
    pdf.set_font('Nanum', '', 11)
    pdf.set_text_color(70, 70, 70)
    
    action_items = report.get('action_items', [])
    for item in action_items:
        # multi_cell은 긴 텍스트의 자동 줄바꿈(Wrap)을 지원합니다.
        pdf.multi_cell(0, 7, str(item).replace('**', '')) # Markdown 볼드체 기호 제거
        pdf.ln(3)
        
    return bytes(pdf.output())
